//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF_Trial1.web_ws {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="web_ws.Ielf_web_ws")]
    public interface Ielf_web_ws {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/CheckParentLogin", ReplyAction="http://tempuri.org/Ielf_web_ws/CheckParentLoginResponse")]
        string CheckParentLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/CheckParentLogin", ReplyAction="http://tempuri.org/Ielf_web_ws/CheckParentLoginResponse")]
        System.Threading.Tasks.Task<string> CheckParentLoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetSubjects", ReplyAction="http://tempuri.org/Ielf_web_ws/GetSubjectsResponse")]
        string GetSubjects(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetSubjects", ReplyAction="http://tempuri.org/Ielf_web_ws/GetSubjectsResponse")]
        System.Threading.Tasks.Task<string> GetSubjectsAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetTestReport", ReplyAction="http://tempuri.org/Ielf_web_ws/GetTestReportResponse")]
        string GetTestReport(int studentId, int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetTestReport", ReplyAction="http://tempuri.org/Ielf_web_ws/GetTestReportResponse")]
        System.Threading.Tasks.Task<string> GetTestReportAsync(int studentId, int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetLessionWiseReport", ReplyAction="http://tempuri.org/Ielf_web_ws/GetLessionWiseReportResponse")]
        string GetLessionWiseReport(int studentId, int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetLessionWiseReport", ReplyAction="http://tempuri.org/Ielf_web_ws/GetLessionWiseReportResponse")]
        System.Threading.Tasks.Task<string> GetLessionWiseReportAsync(int studentId, int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/StudentRegistration", ReplyAction="http://tempuri.org/Ielf_web_ws/StudentRegistrationResponse")]
        string StudentRegistration(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int InstitutionId, int BoardId, int ClassId, int CityId, int DistrictId, int StateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/StudentRegistration", ReplyAction="http://tempuri.org/Ielf_web_ws/StudentRegistrationResponse")]
        System.Threading.Tasks.Task<string> StudentRegistrationAsync(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int InstitutionId, int BoardId, int ClassId, int CityId, int DistrictId, int StateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/ParentRegistration", ReplyAction="http://tempuri.org/Ielf_web_ws/ParentRegistrationResponse")]
        string ParentRegistration(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int CityId, int DistrictId, int StateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/ParentRegistration", ReplyAction="http://tempuri.org/Ielf_web_ws/ParentRegistrationResponse")]
        System.Threading.Tasks.Task<string> ParentRegistrationAsync(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int CityId, int DistrictId, int StateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/StaffRegistration", ReplyAction="http://tempuri.org/Ielf_web_ws/StaffRegistrationResponse")]
        string StaffRegistration(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int BoardId, int ClassId, int SubjectId, int InstitutionId, int CityId, int DistrictId, int StateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/StaffRegistration", ReplyAction="http://tempuri.org/Ielf_web_ws/StaffRegistrationResponse")]
        System.Threading.Tasks.Task<string> StaffRegistrationAsync(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int BoardId, int ClassId, int SubjectId, int InstitutionId, int CityId, int DistrictId, int StateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetCommonData", ReplyAction="http://tempuri.org/Ielf_web_ws/GetCommonDataResponse")]
        string GetCommonData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetCommonData", ReplyAction="http://tempuri.org/Ielf_web_ws/GetCommonDataResponse")]
        System.Threading.Tasks.Task<string> GetCommonDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetClasses", ReplyAction="http://tempuri.org/Ielf_web_ws/GetClassesResponse")]
        string GetClasses(int BoardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetClasses", ReplyAction="http://tempuri.org/Ielf_web_ws/GetClassesResponse")]
        System.Threading.Tasks.Task<string> GetClassesAsync(int BoardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetDistrict", ReplyAction="http://tempuri.org/Ielf_web_ws/GetDistrictResponse")]
        string GetDistrict(int StateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetDistrict", ReplyAction="http://tempuri.org/Ielf_web_ws/GetDistrictResponse")]
        System.Threading.Tasks.Task<string> GetDistrictAsync(int StateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetCities", ReplyAction="http://tempuri.org/Ielf_web_ws/GetCitiesResponse")]
        string GetCities(int StateId, int DistrictId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetCities", ReplyAction="http://tempuri.org/Ielf_web_ws/GetCitiesResponse")]
        System.Threading.Tasks.Task<string> GetCitiesAsync(int StateId, int DistrictId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetInstitutions", ReplyAction="http://tempuri.org/Ielf_web_ws/GetInstitutionsResponse")]
        string GetInstitutions(int StateId, int DistrictId, int CityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetInstitutions", ReplyAction="http://tempuri.org/Ielf_web_ws/GetInstitutionsResponse")]
        System.Threading.Tasks.Task<string> GetInstitutionsAsync(int StateId, int DistrictId, int CityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/CheckStudentLogin", ReplyAction="http://tempuri.org/Ielf_web_ws/CheckStudentLoginResponse")]
        string CheckStudentLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/CheckStudentLogin", ReplyAction="http://tempuri.org/Ielf_web_ws/CheckStudentLoginResponse")]
        System.Threading.Tasks.Task<string> CheckStudentLoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/CheckStaffLogin", ReplyAction="http://tempuri.org/Ielf_web_ws/CheckStaffLoginResponse")]
        string CheckStaffLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/CheckStaffLogin", ReplyAction="http://tempuri.org/Ielf_web_ws/CheckStaffLoginResponse")]
        System.Threading.Tasks.Task<string> CheckStaffLoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetStudentDashboard", ReplyAction="http://tempuri.org/Ielf_web_ws/GetStudentDashboardResponse")]
        string GetStudentDashboard(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetStudentDashboard", ReplyAction="http://tempuri.org/Ielf_web_ws/GetStudentDashboardResponse")]
        System.Threading.Tasks.Task<string> GetStudentDashboardAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetQuestions", ReplyAction="http://tempuri.org/Ielf_web_ws/GetQuestionsResponse")]
        string GetQuestions(int studentId, int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/GetQuestions", ReplyAction="http://tempuri.org/Ielf_web_ws/GetQuestionsResponse")]
        System.Threading.Tasks.Task<string> GetQuestionsAsync(int studentId, int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/SaveUserFeedback", ReplyAction="http://tempuri.org/Ielf_web_ws/SaveUserFeedbackResponse")]
        string SaveUserFeedback(int UserId, string Feedback, string UserType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ielf_web_ws/SaveUserFeedback", ReplyAction="http://tempuri.org/Ielf_web_ws/SaveUserFeedbackResponse")]
        System.Threading.Tasks.Task<string> SaveUserFeedbackAsync(int UserId, string Feedback, string UserType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Ielf_web_wsChannel : ELF_Trial1.web_ws.Ielf_web_ws, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ielf_web_wsClient : System.ServiceModel.ClientBase<ELF_Trial1.web_ws.Ielf_web_ws>, ELF_Trial1.web_ws.Ielf_web_ws {
        
        public Ielf_web_wsClient() {
        }
        
        public Ielf_web_wsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ielf_web_wsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ielf_web_wsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ielf_web_wsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckParentLogin(string username, string password) {
            return base.Channel.CheckParentLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<string> CheckParentLoginAsync(string username, string password) {
            return base.Channel.CheckParentLoginAsync(username, password);
        }
        
        public string GetSubjects(int studentId) {
            return base.Channel.GetSubjects(studentId);
        }
        
        public System.Threading.Tasks.Task<string> GetSubjectsAsync(int studentId) {
            return base.Channel.GetSubjectsAsync(studentId);
        }
        
        public string GetTestReport(int studentId, int subjectId) {
            return base.Channel.GetTestReport(studentId, subjectId);
        }
        
        public System.Threading.Tasks.Task<string> GetTestReportAsync(int studentId, int subjectId) {
            return base.Channel.GetTestReportAsync(studentId, subjectId);
        }
        
        public string GetLessionWiseReport(int studentId, int subjectId) {
            return base.Channel.GetLessionWiseReport(studentId, subjectId);
        }
        
        public System.Threading.Tasks.Task<string> GetLessionWiseReportAsync(int studentId, int subjectId) {
            return base.Channel.GetLessionWiseReportAsync(studentId, subjectId);
        }
        
        public string StudentRegistration(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int InstitutionId, int BoardId, int ClassId, int CityId, int DistrictId, int StateId) {
            return base.Channel.StudentRegistration(FirstName, LastName, EmailAddress, Password, PhoneNumber, InstitutionId, BoardId, ClassId, CityId, DistrictId, StateId);
        }
        
        public System.Threading.Tasks.Task<string> StudentRegistrationAsync(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int InstitutionId, int BoardId, int ClassId, int CityId, int DistrictId, int StateId) {
            return base.Channel.StudentRegistrationAsync(FirstName, LastName, EmailAddress, Password, PhoneNumber, InstitutionId, BoardId, ClassId, CityId, DistrictId, StateId);
        }
        
        public string ParentRegistration(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int CityId, int DistrictId, int StateId) {
            return base.Channel.ParentRegistration(FirstName, LastName, EmailAddress, Password, PhoneNumber, CityId, DistrictId, StateId);
        }
        
        public System.Threading.Tasks.Task<string> ParentRegistrationAsync(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int CityId, int DistrictId, int StateId) {
            return base.Channel.ParentRegistrationAsync(FirstName, LastName, EmailAddress, Password, PhoneNumber, CityId, DistrictId, StateId);
        }
        
        public string StaffRegistration(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int BoardId, int ClassId, int SubjectId, int InstitutionId, int CityId, int DistrictId, int StateId) {
            return base.Channel.StaffRegistration(FirstName, LastName, EmailAddress, Password, PhoneNumber, BoardId, ClassId, SubjectId, InstitutionId, CityId, DistrictId, StateId);
        }
        
        public System.Threading.Tasks.Task<string> StaffRegistrationAsync(string FirstName, string LastName, string EmailAddress, string Password, string PhoneNumber, int BoardId, int ClassId, int SubjectId, int InstitutionId, int CityId, int DistrictId, int StateId) {
            return base.Channel.StaffRegistrationAsync(FirstName, LastName, EmailAddress, Password, PhoneNumber, BoardId, ClassId, SubjectId, InstitutionId, CityId, DistrictId, StateId);
        }
        
        public string GetCommonData() {
            return base.Channel.GetCommonData();
        }
        
        public System.Threading.Tasks.Task<string> GetCommonDataAsync() {
            return base.Channel.GetCommonDataAsync();
        }
        
        public string GetClasses(int BoardId) {
            return base.Channel.GetClasses(BoardId);
        }
        
        public System.Threading.Tasks.Task<string> GetClassesAsync(int BoardId) {
            return base.Channel.GetClassesAsync(BoardId);
        }
        
        public string GetDistrict(int StateId) {
            return base.Channel.GetDistrict(StateId);
        }
        
        public System.Threading.Tasks.Task<string> GetDistrictAsync(int StateId) {
            return base.Channel.GetDistrictAsync(StateId);
        }
        
        public string GetCities(int StateId, int DistrictId) {
            return base.Channel.GetCities(StateId, DistrictId);
        }
        
        public System.Threading.Tasks.Task<string> GetCitiesAsync(int StateId, int DistrictId) {
            return base.Channel.GetCitiesAsync(StateId, DistrictId);
        }
        
        public string GetInstitutions(int StateId, int DistrictId, int CityId) {
            return base.Channel.GetInstitutions(StateId, DistrictId, CityId);
        }
        
        public System.Threading.Tasks.Task<string> GetInstitutionsAsync(int StateId, int DistrictId, int CityId) {
            return base.Channel.GetInstitutionsAsync(StateId, DistrictId, CityId);
        }
        
        public string CheckStudentLogin(string username, string password) {
            return base.Channel.CheckStudentLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<string> CheckStudentLoginAsync(string username, string password) {
            return base.Channel.CheckStudentLoginAsync(username, password);
        }
        
        public string CheckStaffLogin(string username, string password) {
            return base.Channel.CheckStaffLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<string> CheckStaffLoginAsync(string username, string password) {
            return base.Channel.CheckStaffLoginAsync(username, password);
        }
        
        public string GetStudentDashboard(int studentId) {
            return base.Channel.GetStudentDashboard(studentId);
        }
        
        public System.Threading.Tasks.Task<string> GetStudentDashboardAsync(int studentId) {
            return base.Channel.GetStudentDashboardAsync(studentId);
        }
        
        public string GetQuestions(int studentId, int subjectId) {
            return base.Channel.GetQuestions(studentId, subjectId);
        }
        
        public System.Threading.Tasks.Task<string> GetQuestionsAsync(int studentId, int subjectId) {
            return base.Channel.GetQuestionsAsync(studentId, subjectId);
        }
        
        public string SaveUserFeedback(int UserId, string Feedback, string UserType) {
            return base.Channel.SaveUserFeedback(UserId, Feedback, UserType);
        }
        
        public System.Threading.Tasks.Task<string> SaveUserFeedbackAsync(int UserId, string Feedback, string UserType) {
            return base.Channel.SaveUserFeedbackAsync(UserId, Feedback, UserType);
        }
    }
}
